cask_args appdir: '/Applications'
tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/services'
tap 'neovim/neovim'
tap 'caskroom/versions'
tap 'domt4/autoupdate'

# basic needs
brew 'direnv'
brew 'git'
brew 'go'
brew 'hub'
brew 'neovim'
brew 'node'
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'python'
brew 'rbenv'
brew 'reattach-to-user-namespace'
brew 'tmux'
brew 'wget'
brew 'zsh'
cask 'osxfuse'
brew 'ntfs-3g'

# local services
brew 'postgresql'
brew 'redis', restart_service: true
brew 'sqlite'

# grpc and protobuf
brew 'protobuf'

# k8s
brew 'kubernetes-cli'
brew 'kubectx'

# utilities
brew 'pandoc'
brew 'the_silver_searcher'
brew 'ripgrep'
brew 'watchman'
brew 'yarn'
brew 'youtube-dl'

# casks
cask '1password'
cask 'appcleaner'
cask 'backblaze'
cask 'bettertouchtool'
cask 'discord'
cask 'docker'
cask 'emacs'
cask 'firefox-developer-edition'
cask 'google-chrome'
cask 'iterm2'
cask 'java'
cask 'karabiner-elements'
cask 'omnifocus'
cask 'postgres'
cask 'postman'
cask 'slack'
cask 'spectacle'
cask 'spotify'
cask 'sublime-text'
cask 'telegram'
cask 'the-unarchiver'
cask 'transmission'
cask 'tunnelblick'
